### ISSUE TITLE
Please add a wheel for Windows for Python 3.13

### ISSUE THREAD

**Issue by joanise** [aflc/editdistance#115]
Currently, `pip install editdistance` works on Linux with Python 3.13, but not on Windows, due to compilation errors. Please build wheels for py 3.13, to fix this issue.

**Comment by darkness-A** [comment]
pip install git+https://github.com/roy-ht/editdistance.git

**Comment by joanise** [comment]
Sure enough @1756816846 that works today on the computer where I just tried. It did not work when I submitted this issue. I'm not sure what's changed, but I can close this issue.

**Comment by joanise** [comment]
Unfortunately, this work-around no longer works, and even if it did, it would not be general solution: projects using `editdistance` should be able to depend on it by version and rely on PyPI as the source.

**Comment by darkness-A** [comment]
I forgot why I used this library

**Comment by darkness-A** [comment]
> Unfortunately, this work-around no longer works, 和 even if it did, it would not be general solution: projects using `editdistance` should be able to depend on it by version and rely on PyPI as the source.

I forgot why I used this library

**Comment by joanise** [comment]
> I forgot why I used this library

As a fast implementation of the Levenshtein distance, it's potentially useful in all sorts of projects. For us, it is an indirect dependency introduced by the panphon library.
